- Jenkinsfile
- empty-plugin/pom.xml
- empty-plugin/src/test/resources/projects/testInstall/archetype.properties
- empty-plugin/src/test/resources/projects/testInstall/goal.txt
- empty-plugin/src/test/resources/projects/testInstall/reference/pom.xml
- empty-plugin/src/test/resources/projects/testInstall/reference/src/main/resources/index.jelly
To test this run:
```
mvn clean install archetype:integration-test
```
> Add integration tests to empty plugin.

- Jenkinsfile
- settings-azure.xml
Should avoid getting us blacklisted by Central!
> Using Azure mirror for builds

- pom.xml
Useful when testing interactively in other ways.
> Honor -DskipTests

- hello-world/src/main/resources/archetype-resources/pom.xml
> Cleaning up hello-world-plugin POM

- hello-world/src/test/resources/projects/testInstall/archetype.properties
- hello-world/src/test/resources/projects/testInstall/goal.txt
> Added test for hello-world-plugin.

- hello-world/src/main/resources/archetype-resources/src/main/resources/HelloWorldBuilder/config_de.properties
- hello-world/src/main/resources/archetype-resources/src/main/resources/HelloWorldBuilder/help-name_de.html
- hello-world/src/main/resources/archetype-resources/src/main/resources/HelloWorldBuilder/help-useFrench_de.html
- hello-world/src/main/resources/archetype-resources/src/main/resources/Messages_de.properties
> Add German localization

- Jenkinsfile
- pom.xml
> For now, keep archetypes using jenkins-pipeline-unit in an optional profile

- pom.xml
So no need to log in to Nexus UI. Maybe should be the default in the parent POM?
> autoReleaseAfterClose

- empty-plugin/pom.xml
- hello-world/pom.xml
- pom.xml
- scripted-pipeline/pom.xml
[Docs](https://maven.apache.org/archetype/archetype-packaging/)
> archetype-packaging needed to update catalogs

- global-configuration/pom.xml
- global-configuration/src/main/resources/META-INF/maven/archetype-metadata.xml
- global-configuration/src/main/resources/archetype-resources/.gitignore
- global-configuration/src/main/resources/archetype-resources/pom.xml
- global-configuration/src/main/resources/archetype-resources/src/main/java/SampleConfiguration.java
- global-configuration/src/main/resources/archetype-resources/src/main/resources/SampleConfiguration/config.jelly
- global-configuration/src/main/resources/archetype-resources/src/main/resources/SampleConfiguration/help-label.html
- global-configuration/src/main/resources/archetype-resources/src/main/resources/index.jelly
- global-configuration/src/main/resources/archetype-resources/src/test/java/SampleConfigurationTest.java
- global-configuration/src/test/resources/projects/testInstall/archetype.properties
- global-configuration/src/test/resources/projects/testInstall/goal.txt
- pom.xml
> Global configuration plugin example

- Jenkinsfile
> Do not use pipeline-unit profile

- empty-plugin/src/main/resources/archetype-resources/pom.xml
- global-configuration/src/main/resources/archetype-resources/pom.xml
- global-shared-library/src/main/resources/archetype-resources/unit-tests/pom.xml
- hello-world/src/main/resources/archetype-resources/pom.xml
- scripted-pipeline/src/main/resources/archetype-resources/pom.xml
Filing based on comments in [jenkinsci/jenkins#3147](https://github.com/jenkinsci/jenkins/pull/3147#pullrequestreview-83880198).
@reviewbybees
> Update wiki urls and use https for license urls

- empty-plugin/src/main/resources/archetype-resources/pom.xml
- global-configuration/src/main/resources/archetype-resources/pom.xml
- hello-world/src/main/resources/archetype-resources/pom.xml
> <url> on wiki.jenkins.io meaningful only for plugins actually hosted in the @jenkinsci org

- empty-plugin/src/main/resources/archetype-resources/pom.xml
- global-configuration/src/main/resources/archetype-resources/pom.xml
- hello-world/src/main/resources/archetype-resources/pom.xml
> Use new parent versions

- pom.xml
Has been useful in other repos.
@reviewbybees
> Added skip-tests-on-release profile

- Dockerfile
- Jenkinsfile
- empty-plugin/src/test/resources/projects/testInstall/goal.txt
- global-configuration/src/test/resources/projects/testInstall/goal.txt
- global-shared-library/src/test/resources/projects/testInstall/goal.txt
- hello-world/src/test/resources/projects/testInstall/goal.txt
- scripted-pipeline/src/test/resources/projects/testInstall/goal.txt
Makes for a more easily reproduced build, as in https://github.com/jenkinsci/docker-workflow-plugin/pull/105, which should help with issues like that in #41.
Uses https://github.com/moby/moby/issues/14080 for caching.
> Switch Jenkinsfile to run docker-build explicitly

- global-shared-library/src/main/resources/archetype-resources/unit-tests/pom.xml
- scripted-pipeline/src/main/resources/archetype-resources/pom.xml
> Bump groovy-eclipse-compiler from 2.9.2-01 to 3.4.0-01

- Jenkinsfile
Looking for a workaround for [INFRA-2197](https://issues.jenkins-ci.org/browse/INFRA-2197).
> [INFRA-2197] docker system prune --all --force

- empty-plugin/src/main/resources/archetype-resources/pom.xml
- global-configuration/src/main/resources/archetype-resources/pom.xml
- hello-world/src/main/resources/archetype-resources/pom.xml
[Background](https://groups.google.com/d/msg/jenkinsci-dev/VSdfVMDIW-A/vqXxJiI7AQAJ)
> [JENKINS-59195] Switch recommended /project/url from Confluence to GitHub

- Dockerfile
- settings-azure.xml
Similar to [jenkins-infra/pipeline-library#135](https://github.com/jenkins-infra/pipeline-library/pull/135)
> Revert repo.azure.jenkins.io to repo.jenkins-ci.org

- empty-plugin/src/main/resources/archetype-resources/pom.xml
- global-configuration/src/main/resources/archetype-resources/pom.xml
- hello-world/src/main/resources/archetype-resources/pom.xml
See https://github.com/jenkinsci/bom/pull/255. Good time to update.
> Switch plugin samples to 2.235.x

- hello-world/src/main/resources/archetype-resources/pom.xml
Amends #155; forgotten in https://github.com/jenkinsci/archetypes/pull/155/commits/42d5ed91c7bb8fd0620b07d6f367bca83737661a.
> Forgot to make license conditional for hello-world

- common-files/.mvn/extensions.xml
- empty-plugin/src/main/resources/archetype-resources/pom.xml
- global-configuration/src/main/resources/archetype-resources/pom.xml
- hello-world/src/main/resources/archetype-resources/pom.xml
Matches https://github.com/jenkinsci/incrementals-tools/pull/16.
> [JENKINS-58716] Using gitHubRepo

- hello-world/src/main/resources/archetype-resources/src/main/java/HelloWorldBuilder.java
Pick up https://github.com/jenkinsci/jenkins/pull/4766 now that we are on a suitably new baseline.
> [JENKINS-29144] Use new overload of SimpleBuildStep.perform

- empty-plugin/pom.xml
- empty-plugin/src/main/resources/archetype-resources/pom.xml
- global-configuration/pom.xml
- global-configuration/src/main/resources/archetype-resources/pom.xml
- hello-world/pom.xml
- hello-world/src/main/resources/archetype-resources/pom.xml
- pom.xml
Adopts the [POM Code Convention](https://maven.apache.org/developers/conventions/code.html#pom-code-convention) that was [voted on by Maven developers in 2008](https://lists.apache.org/thread/h8px5t6f3q59cnkzpj1t02wsoynr3ygk). Note that this PR adds no automation; this is just a one-time pass.
> Adopt POM Code Convention

- empty-plugin/src/main/resources/archetype-resources/pom.xml
https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/
> Bump minimum version to recommended one

- common-files/.github/dependabot.yml
Fixes https://github.com/jenkinsci/archetypes/issues/288.
> Default to only monthly updates for Dependabot

- global-configuration/src/main/resources/archetype-resources/pom.xml
- hello-world/src/main/resources/archetype-resources/pom.xml
This comment hasn't been true since March 2021.
> Remove commented out developers section and wrong comment

- common-files/Jenkinsfile
https://github.com/jenkinsci/archetypes/pull/547#discussion_r1039530149
> Remove linux 11 from CI testing by default

- empty-plugin/src/main/resources/archetype-resources/pom.xml
- global-configuration/src/main/resources/archetype-resources/pom.xml
- hello-world/src/main/resources/archetype-resources/pom.xml
The templating directive #end seems to eat the next end-of-line, causing incorrect formatting on the resulting file.
This adds additional newlines so that the resulting file looks better.
> Add missing end-of-line

- common-files/.github/workflows/jenkins-security-scan.yml
https://github.com/jenkinsci/archetypes/pull/597#discussion_r1124375469
> Use redirect URL

- empty-plugin/src/main/resources/archetype-resources/pom.xml
- global-configuration/src/main/resources/archetype-resources/pom.xml
- global-configuration/src/main/resources/archetype-resources/src/main/java/SampleConfiguration.java
- global-configuration/src/main/resources/archetype-resources/src/test/java/SampleConfigurationTest.java
- hello-world/src/main/resources/archetype-resources/pom.xml
- hello-world/src/main/resources/archetype-resources/src/main/java/HelloWorldBuilder.java
- hello-world/src/main/resources/archetype-resources/src/test/java/HelloWorldBuilderTest.java
Fixes #614 by enabling Spotless for all three archetypes and ensuring the existing archetype code complies. To test this I generated projects from all three archetypes and verified that `mvn clean verify` worked on all three, including running Spotless. Please review with the **Hide Whitespace** feature enabled.
> Enable Spotless

- empty-plugin/src/main/resources/archetype-resources/pom.xml
- global-configuration/src/main/resources/archetype-resources/pom.xml
- global-configuration/src/main/resources/archetype-resources/src/test/java/SampleConfigurationTest.java
- hello-world/src/main/resources/archetype-resources/pom.xml
Similar to https://github.com/jenkinsci/archetypes/pull/632, but with the mandatory changes for HTMLUnit.
I couldn't check out the dependabot branch locally for some reason, therefore I created a new PR.
Closes https://github.com/jenkinsci/archetypes/pull/632
> Update pom to 4.66

- pom.xml
Closes https://github.com/jenkinsci/archetypes/pull/646
Thanks for approving my OSSRH issue!
> Replace `org.kohsuke:pom` with `io.jenkins.tools:central-repository-pom`

- README.md
Most recent release is a better example
Confirmed that the new command works as expected with Java 11 on Linux
> Use most recent release in example docs

- README.md
ref. https://github.com/jenkins-infra/helpdesk/issues/3599
> chore(docs) update README to exclude central repository from mirror

- common-files/.mvn/extensions.xml
Twin of https://github.com/jenkinsci/archetypes/pull/685, but for incrementals.
> Update schemaLocation of extensions.xml

- common-files/.github/workflows/jenkins-security-scan.yml
With https://github.com/jenkinsci/jenkins/pull/9358 in effect, it makes sense to upgrade the action to run with Java 17.
None.
> Update java-version to 17 for Jenkins Security Scan

- empty-plugin/src/main/resources/archetype-resources/pom.xml
- global-configuration/src/main/resources/archetype-resources/pom.xml
- hello-world/src/main/resources/archetype-resources/pom.xml
see https://github.com/jenkinsci/ssh-credentials-plugin/pull/210#discussion_r1688685749 and its happened plenty of others
Works with:
- dependabot: https://github.com/jenkinsci/analysis-pom-plugin/pull/958
- renovate: https://github.com/jenkinsci/junit-plugin/pull/616
> Add jenkins.baseline variable to reduce manual bom update mistakes

- common-files/.github/workflows/jenkins-security-scan.yml
In order to unify the actions configuration this PR will
_Please note this PR was created semi-automatically. If you find any issue with it, don't hesitate to ping me._
_See discussion in https://github.com/jenkinsci/asm-api-plugin/pull/36_
Awaiting run of the action to verify the changes...
> Update Jenkins Security Scan action

- common-files/Jenkinsfile
https://www.kernel.org/doc/html/latest/process/coding-style.html#commenting
> Fix block comment style

- theme-plugin/src/main/resources/archetype-resources/src/main/webapp/__theme__.css
Add teal (and light/dark alternatives) to the base css
Also I've reordered the colours to be ROYGBIV(ish)
> impr: add teal to the base css for the theme plugin

- .github/updatecli/updatecli.d/jenkins-baseline.yaml
Follow up to #833
The targets need to have a source control management id so that the changes made are applied
> fix: add source control management ids to the targets

- pom.xml
> Add timja to maintainers
