jenkinsci/archetypes

empty-plugin/pom.xml, scripted-pipeline/pom.xml
Seems to be necessary to show some kind of information from `archetype:generate`.
=> Adding descriptions to archetypes

empty-plugin/src/main/resources/archetype-resources/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml
Versions before 2.35 have issues with running JenkinsRule tests in IDEA, so I propose to fix that by just bumping versions.
@reviewbybees @jglick @Wadeck
=> Update plugin POMs to the latest versions

empty-plugin/src/main/resources/META-INF/maven/archetype-metadata.xml, empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/META-INF/maven/archetype-metadata.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, global-configuration/src/test/resources/projects/testInstall/archetype.properties, global-shared-library/src/main/resources/META-INF/maven/archetype-metadata.xml, global-shared-library/src/test/resources/projects/testInstall/archetype.properties, hello-world/src/main/resources/META-INF/maven/archetype-metadata.xml, hello-world/src/main/resources/archetype-resources/pom.xml, hello-world/src/test/resources/projects/testInstall/archetype.properties, scripted-pipeline/src/main/resources/META-INF/maven/archetype-metadata.xml, scripted-pipeline/src/test/resources/projects/testInstall/archetype.properties
If nothing else, keeps people from trying to remember whether to use `jenkinsci`, `jenkins_ci`, `jenkinsCi`, etc.
@reviewbybees
=> Use io.jenkins as the default package prefix for new code

empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml
Cleanup from https://github.com/jenkins-infra/update-center2/pull/204.
=> Omitting redundant <description> in new plugin pom.xml since src/main/resources/index.jelly now suffices in all cases

.github/release-drafter.yml, README.md
See https://groups.google.com/forum/#!msg/jenkinsci-dev/dOs8YRQwQiI/jPH0e_yTBQAJ for the context. IMHO we could update all dev tool repos to save our time
=> Move the changelog to GitHub releases, powered by Release Drafter

README.md
[JENKINS-58040](https://issues.jenkins-ci.org/browse/JENKINS-58040) When using the following minimal maven `settings.xml`, no jenkinsci archetypes can be found
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
http://maven.apache.org/xsd/settings-1.0.0.xsd">
<localRepository/>
<interactiveMode/>
<usePluginRegistry/>
<offline/>
<pluginGroups/>
<servers/>
<mirrors>
<mirror>
<id>repo.jenkins-ci.org-all</id>
<url>https://repo.jenkins-ci.org/public</url>
<mirrorOf>*</mirrorOf>
</mirror> 
</mirrors>
<proxies/>
<profiles/>
<activeProfiles/>
</settings>
```
```
platypus:mvn_test domi$ docker run -ti --rm -v "/tmp/dummy/settings.xml":/root/.m2/settings.xml --name mvn …
```
=> [JENKINS-58040] make note about mirror limitation in settings.xml

Jenkinsfile, empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, global-shared-library/src/main/resources/archetype-resources/unit-tests/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml, scripted-pipeline/src/main/resources/archetype-resources/pom.xml
Update jenkins.version and java.level so that plugins generated from the archetype support Java 8 and Java 11.
Update other dependencies to allow Java 8 and Java 11.
=> Update plugin archetype for Java 11 - JENKINS-57341

.dependabot/config.yml, pom.xml
I requested access for Dependabot to this repo, but I am not an admin of it (only have write access); any way to find out who _is_ an admin?
=> Enable Dependabot for the repository

README.md, empty-plugin/src/main/resources/META-INF/maven/archetype-metadata.xml, global-configuration/src/main/resources/META-INF/maven/archetype-metadata.xml, global-shared-library/src/main/resources/META-INF/maven/archetype-metadata.xml, hello-world/src/main/resources/META-INF/maven/archetype-metadata.xml, pom.xml, scripted-pipeline/src/main/resources/META-INF/maven/archetype-metadata.xml
ref: https://stackoverflow.com/a/46876927/4951015
To test:
```
mvn clean install -DskipTests # tests take awhile, generation is instant without
```
create a directory somewhere and enter it then:
```
mvn archetype:generate -B -DarchetypeGroupId=io.jenkins.archetypes -DarchetypeArtifactId=global-configuration-plugin -DarchetypeVersion=1.8-SNAPSHOT -DartifactId=cool-thing
```
=> Fix missing gitignore

common-files/.mvn/maven.config
Amends #155. See https://github.com/jenkinsci/incrementals-tools/blob/f6fb2fd644fa0aa7be5c5173506d9368b542dd2d/maven-plugin/src/main/java/io/jenkins/tools/incrementals/maven/IncrementalifyMojo.java#L99
=> Mistyped names of Incrementals profiles

common-files/README.md
Amends #155. Does not really make sense for an in-house plugin, etc., and at a minimum they would not get access to the @jenkinsci defaults.
=> Section on Contributing was specific to @jenkinsci

empty-plugin/src/main/resources/META-INF/maven/archetype-metadata.xml, global-configuration/src/main/resources/META-INF/maven/archetype-metadata.xml, hello-world/src/main/resources/META-INF/maven/archetype-metadata.xml
Amending #155. Noticed because the NetBeans project wizard for Jenkins plugins broke. Does not work perfectly for reasons detailed in [ARCHETYPE-308](https://issues.apache.org/jira/browse/ARCHETYPE-308) (in particular, cannot simplify `*/src/test/resources/projects/testInstall/archetype.properties`), and also I stumbled across [ARCHETYPE-539](https://issues.apache.org/jira/browse/ARCHETYPE-539) which explains why it is so excruciatingly slow to test changes here.
=> Set a defaultValue for hostOnJenkinsGitHub

common-files/.github/dependabot.yml, common-files/.github/workflows/release-drafter.yml
https://github.com/release-drafter/release-drafter/pull/742 is significant.
=> Pin the version of Release Drafter, but include in Dependabot

common-files/README.md
These are all showing the same information displayed elsewhere on the same page (plugin site or GitHub repo index page) already, so bring little or no value.
If individual maintainers want to display these, they're can always add them, but there's no reason this should be a project-wide default.
=> Remove badges

empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml
We normally let archetypes lag somewhat behind on `jenkins.version`, but given the magnitude of the changes in 2.277.x I think it does not make much sense to develop new plugins against earlier lines.
=> Switch archetypes to 2.277.x line

global-configuration/src/main/resources/archetype-resources/src/test/java/SampleConfigurationTest.java
We seem to be generally preferring `JenkinsSessionRule` to `RestartableJenkinsRule`. The main benefit to `JenkinsSessionRule` is that `#then` runs immediately, so it plays nicely with things like `@After`.
=> Migrate from `RestartableJenkinsRule` to `JenkinsSessionRule`

empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml
Not to start a holy war or anything, but I think we should use HTTPS rather than SSH protocol for all `/project/scm`URLs. Currently we do so for `url` but use SSH for `developerConnection` and :warning: unencrypted anonymous Git protocol for `connection`. I suggest we normalize to HTTPS as the most generic, cross-platform, and contemporary protocol.
* https://stackoverflow.com/q/11041729/12916 is unclear
* https://gist.github.com/grawity/4392747 is pretty old (e.g. predates the fact that the `gh` CLI uses HTTPS)
* https://docs.github.com/en/github/using-git/which-remote-url-should-i-use is agnostic
* https://maven.apache.org/pom.html#SCM is spectacularly unhelpful (CVS?!)
Need to verify that `plugin-compat-tester` is not going to explode though. (That is basically the only consumer of the …
=> Use HTTPS protocol for all github.com SCM URLs

empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml, pom.xml
Generalizing https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/465 to other plugins. Only relevant for repositories using `<modules>`, which none of these examples do, but so hard to track down when you need it that it seems best to just define it everywhere.
=> Set `child.scm.*.inherit.append.path=false`

empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml
https://github.com/jenkinsci/archetypes/pull/371#pullrequestreview-843049292
=> Bump bom and other archetypes to 2.303

empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml
Adapts to [4.40](https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.40).
=> Remove deprecated `java.level` property

Dockerfile
Also removing the `-openjdk-11` part so Dependabot can keep this up to date.
=> Bump Maven from 3.8.1 to 3.8.4

README.md, common-files/.github/dependabot.yml, common-files/.github/workflows/release-drafter.yml, common-files/.mvn/extensions.xml
This PR addresses a few common issues, I'm always highlighting when reviewing hosting requests.
Additionally, I replaced the dependabot help URL with a working one and reduced the runs from monthly to weekly. Given, a lot of plugins and components use JEP-229 nowadays, releases happen much more frequent, than on a monthly basis.
=> Pin release-drafter, bump git-changelist-maven-extension and fix dependabot URL

common-files/Jenkinsfile, empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml
Closes #542. Also see https://github.com/jenkins-infra/jenkins.io/pull/5731. As per https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/ we should perhaps wait until 2.375.1 is released, though that should happen by the time this PR actually goes live anyway.
=> Switch default baseline for new plugins to 2.361.x

common-files/Jenkinsfile
=> Add Java 17 to recommended configurations

common-files/Jenkinsfile
The comment about 'docker' can be misleading. 
- The pipeline library abstracts away the logic around the concept of a "docker" platform
- Docker on containerized agent is not provided for security reasons (Docker in docker not allowed on ci.jenkins.io)
- Windows Docker works if needed
=> fix(buildPlugin pipeline library) Correct instruction to use Docker containerized tests

.github/dependabot.yml
dependabot can't detect files outside the common directories, hence we need to use a direct path.
=> Use proper path for dependabot common-files directory

common-files/.mvn/extensions.xml
=> Update git-changelist-maven-extension from 1.5 to 1.6

common-files/.github/workflows/jenkins-security-scan.yml
New hosting requests are reviewed initially by our set of predefined CodeQL rules. The recent hosting requests subject to the new scanning showed long lists of issues (including a few false-positives).
Therefore, I'm assuming a lack of awareness of how to mitigate, and even better, avoid introducing possible security vulnerabilities in your plugin.
For this reasoning, I would like to include the security scan by default in all new plugins, to raise awareness of possible security issues and give maintainers an opportunity, to react to issues.
=> Add Jenkins security scan to common files

empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml
2.361.4 is subject to [seven](https://www.jenkins.io/security/advisory/2023-03-08/) different security vulnerabilities, and has been removed from the BOM. It doesn't make a good fit as plugin baseline anymore.
The change proposed updates the baseline to 2.375.4 and updates the license URL, which currently relies on a redirect.
=> Bump baseline from 2.361.4 to 2.375.4

empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml
A good point brought up by Mark in https://github.com/jenkinsci/archetypes/pull/628#issuecomment-1573948518, highlighting that the baseline 2.375 will be EOL in 6 months anyway, making it not the best future-proof approach.
The change proposed bumps the baseline to 2.387.3, making it a longer approach.
=> Bump baseline from 2.375 to 2.387

hello-world/src/main/resources/archetype-resources/src/test/java/HelloWorldBuilderTest.java
Spotless reformatting (#619) defeated the purpose of the original manual formatting, which was to show the indentation of the Groovy script embedded in Java sources. This just seems to be impossible in Spotless, at least until we are on a new enough version of Java that we can use multiline string literals. (Some projects also use external `src/test/resources/**/*.groovy`, which has its own advantages of course, but forces readers and editors to flip back and forth between files for a single test case.)
=> Improve formatting in `HelloWorldBuilderTest`

common-files/Jenkinsfile
=> Update default Jenkinsfile to include Java 21

common-files/Jenkinsfile
apply a default initial `forkCount` of `1C` to new plugins to speedup the build.
The number has been chosen from a commonly used number in Jenkinsfils in use on several plugins in the community.
Some are of the opinion that the archetype offers the best practices (they do not exist) and changes to the pipeline should be reflected in all plugins (or the top 200).  I will not be suggesting these changes to any plugins, as the suggestion may be sub-optimal, rather the plugins maintainers should experiment themselves to find and set an optimal value.   Having said this - I still believe it makes sense to advertise (and set a default) for new plugins.
`forkCount` has been used in several plugins already.  this exact Jenkinsfile has not been tested
```[tasklist]
```
=> apply a default initial `forkCount` of `1C` to new plugins to speedup the build.

empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml
While using the maven tidy plugin in another repository, I noticed that not only the POM has been tidied, but the XML namespace location has been changed too.
Given this is a trivial change because http://maven.apache.org/maven-v4_0_0.xsd redirects to https://maven.apache.org/xsd/maven-4.0.0.xsd, I'd propose we update it still, to align with the maven POM code convention and ensure future plugins use the up-to-date schema location URL.
=> Update XML namespace schemaLocation

empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml
2.387.3 is already gone from the recommended baseline pages, due to its age. I propose we move on to 2.414.3 because 2.401.3 will vanish next week too when we decide a new baseline.
=> Bump baseline from 2.387.3 to 2.414.3

common-files/archetype-post-generate.groovy, empty-plugin/src/main/resources/archetype-resources/pom.xml, empty-plugin/src/test/resources/projects/testInstallNoGithub/archetype.properties, empty-plugin/src/test/resources/projects/testInstallNoGithub/goal.txt, global-configuration/src/main/resources/archetype-resources/pom.xml, global-configuration/src/test/resources/projects/testInstallNoGithub/archetype.properties, global-configuration/src/test/resources/projects/testInstallNoGithub/goal.txt, hello-world/src/main/resources/archetype-resources/pom.xml, hello-world/src/test/resources/projects/testInstallNoGithub/archetype.properties, hello-world/src/test/resources/projects/testInstallNoGithub/goal.txt
Fixes #709 
The fix itself was trivial.
I added integration tests specifically for that scenario, but the tests broke with spotbugs errors (for the generated POM).  Example (snippet):
```
[INFO] [ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.43.0:check (default) on project testArtifact: The following files had format violations:
[INFO] [ERROR]     pom.xml
[INFO] [ERROR]         @@ -15,16 +15,14 @@
[INFO] [ERROR]          ··<packaging>hpi</packaging>
[INFO] [ERROR]          
[INFO] [ERROR]          ··<name>TODO·Plugin</name>
[INFO] [ERROR]         -··
[INFO] [ERROR]         -··
[INFO] [ERROR]         -··
[INFO] [ERROR]         +
[INFO] [ERROR]          ··<properties>
[INFO] [ERROR]          ····<revision>1.0</revision>
[INFO] [ERROR] …
```
=> Fix generation of repos using  `-DhostOnJenkinsGitHub=false`

empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml
In a couple of weeks, we will choose a new baseline and 2.440.3 will be the second oldest baseline to build against.
=> Update Jenkins baseline to 2.440.3

.github/renovate.json
Projects configured from the archetype most often prefer to depend on the last release of a recent LTS line.  The archetype currently requires Jenkins 2.440.3 or newer.  When we switch to parent pom 5.x, we'll need to require Jenkins 2.475 (weekly) or Jenkins 2.479.x (LTS).
I think it will be several months before we're ready to switch the archetype to use plugin parent pom 5.x.  Until that time, this configures renovate to only recommend versions less than 5.x
Installed the renovate-config-validator locally with commands:
$ nvm install --lts
$ npx --yes --package renovate -- renovate-config-validator
Ran the configuration validator with
$ renovate-config-validator
Before this change, reported that migration was needed.  After this change, it no longer reports that migration is needed. …
=> Exclude parent pom 5.x from renovate updates

empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml
Similar to https://github.com/jenkinsci/archetypes/pull/735 
Would be nice to have a release to avoid new plugin be created with 2.440
mvn clean install
=> Require 2.452.4

global-configuration/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/src/test/java/SampleConfigurationTest.java, hello-world/src/main/resources/archetype-resources/src/test/java/HelloWorldBuilderTest.java
Re-opened from https://github.com/jenkinsci/archetypes/pull/691
> It should be considered best practice to start plugin development using JUnit5 over JUnit4. 
> 
> * `org.junit.*` imports being updated to JUnit5 equivalents
> * Use `@WithJenkins` in combination with `JenkinsRule`
> * Make test classes and methods package-private (convention for JUnit5)
> 
> I'm not 100% convinced that I migrated `SampleConfigurationTest` correctly since I was not able to find a proper equivalent for `JenkinsSessionRule` - maybe @basil could confirm if the test still covers the intended functionality.
Now that https://github.com/jenkinsci/jenkins-test-harness/pull/716 was merged there is a clean way to implement `SampleConfigurationTest.java` with JUnit5.
Creating this as a draft, since it depends on …
=> Upgrade tests to use JUnit5

hello-world/src/main/resources/archetype-resources/pom.xml
the structs plugin is usually not needed.
It is only needed when a plugin needs to lookup symbols but not when you just use the `@Symbol` annotation
=> remove dependency to structs plugin

.github/renovate.json, pom.xml
Reverts https://github.com/jenkinsci/archetypes/pull/763, because 2.479 is now being used as baseline in the different archetypes.
=> Remove ban on renovate updates for 5.x pom

global-configuration/src/main/resources/archetype-resources/src/main/java/SampleConfiguration.java
Simpler and more explicitly to use the standard JDK libraries here.
=> Remove usages of Commons Lang from example plugin

theme-plugin/src/main/resources/archetype-resources/pom.xml, theme-plugin/src/main/resources/archetype-resources/src/main/java/__themeClassNameTheme.java, theme-plugin/src/main/resources/archetype-resources/src/test/java/jcasc/AbstractThemeJCasCTest.java, theme-plugin/src/main/resources/archetype-resources/src/test/java/playwright/AppearancePage.java, theme-plugin/src/main/resources/archetype-resources/src/test/java/playwright/__themeClassNameThemeTest.java
Ensure that projects generated by the theme plugin archetype have spotless applied by default.
This PR enables that setting as well as fixes up formatting issues within the archetype resources to ensure that there are no issues with the generated code.
`mvn clean verify`
=> Apply spotless by default for theme-plugin

empty-plugin/src/main/resources/archetype-resources/pom.xml, global-configuration/src/main/resources/archetype-resources/pom.xml, hello-world/src/main/resources/archetype-resources/pom.xml, theme-plugin/src/main/resources/archetype-resources/pom.xml
Picks up the latest addition of the plugin pom, to stop the introduction of the deprecated library.
=> Ban JUnit 4
